openapi: 3.0.0
info:
  title: Online Bookstore API
  version: 1.0.0
  description: API documentation for an online bookstore.
servers:
  - url: https://api.example.com/v1
paths:
  /books:
    get:
      summary: Get list of books
      parameters:
        - name: page
          in: query
          description: Page number for pagination
          schema:
            type: integer
        - name: limit
          in: query
          description: Number of items per page
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
  /books/search:
    get:
      summary: Search books by title or author
      parameters:
        - name: query
          in: query
          description: Search query
          schema:
            type: string
            example: "Harry Potter"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
  /books/{isbn}:
    get:
      summary: Get book by ISBN
      parameters:
        - name: isbn
          in: path
          description: ISBN of the book to be retrieved
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
  /cart:
    post:
      summary: Create a new shopping cart
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  cartId:
                    type: string
  /cart/{cartId}/items:
    post:
      summary: Add a book to the cart
      parameters:
        - name: cartId
          in: path
          description: Cart ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                isbn:
                  type: string
                  description: ISBN of the book to be added
                quantity:
                  type: integer
                  description: Quantity of the book to be added
      responses:
        '200':
          description: Successful response
  /cart/{cartId}/items/{isbn}:
    delete:
      summary: Remove a book from the cart
      parameters:
        - name: cartId
          in: path
          description: Cart ID
          required: true
          schema:
            type: string
        - name: isbn
          in: path
          description: ISBN of the book to be removed
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No content
    patch:
      summary: Update quantity of a book in the cart
      parameters:
        - name: cartId
          in: path
          description: Cart ID
          required: true
          schema:
            type: string
        - name: isbn
          in: path
          description: ISBN of the book to be updated
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  description: New quantity of the book in the cart
      responses:
        '200':
          description: Successful response
  /cart/{cartId}:
    get:
      summary: Get current state of the cart
      parameters:
        - name: cartId
          in: path
          description: Cart ID
          required:
          
